pipeline:
  setup_site:
    image: python:3-slim
    commands:
      - pip install -r requirements.txt
      - mkdocs build --clean
  build-image:
    image: hub.gyg.io/drone-plugins/gyg-registry
    context: .
    dockerfile: ./Dockerfile
    repo: hub.gyg.io/devops/incident-response-docs
    tags:
      - ${DRONE_BUILD_NUMBER}.${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
  register-dss:
    image: hub.gyg.io/drone-plugins/dss
    repo: hub.gyg.io/devops/incident-response-docs
    tags:
      - ${DRONE_BUILD_NUMBER}.${DRONE_COMMIT_SHA:0:7}
    when:
      event: push
