version: 2.1

# The environment in which our build/deploy will run. Gives us a single place to define the image we use.
executors:
  build_env:
    docker:
      - image: circleci/python:3.9.2

# Defines how to build the docs, and how to deploy them. We'll re-use these bits later.
commands:
  build_docs:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo pip install mkdocs
            sudo pip install pymdown-extensions
            sudo pip install pygments
      - run:
          name: Install Theme
          command: |
            git clone https://github.com/pagerduty/mkdocs-theme-pagerduty
            cd mkdocs-theme-pagerduty && sudo python3 setup.py install
      - run:
          name: Build Site
          command: |
            mkdocs build --clean

  deploy_docs:
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo pip install awscli
      - run:
          name: Deploy to S3
          # Use --delete to remove any old files from bucket too, so we don't keep stale info around.
          command: |
            aws s3 sync site/ s3://$AWS_S3_BUCKET --acl public-read --cache-control "max-age=86400" --exclude "*.py*" --delete
      - run:
          name: Invalidate CloudFront Cache
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"

# We only have two jobs, one builds the docs, the other both builds and deploys them.
jobs:
  build:
    executor: build_env
    steps:
      - build_docs

  deploy:
    executor: build_env
    steps:
      - build_docs
      - deploy_docs

# Just the one workflow. It always builds, buy only deploys when on the master branch.
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
