version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: 'sudo pip install mkdocs-bootswatch==0.1.0'
      - run: 'sudo pip install mkdocs-bootstrap==0.1.1'
      - run: 'sudo pip install mkdocs==0.15.3'
      - run: 'sudo pip install mkdocs-material==0.2.4'
      - run: 'sudo pip install pymdown-extensions'
      - run: 'mkdocs build --clean'

  deploy:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: 'sudo pip install awscli'
      - run: 'sudo pip install mkdocs-bootswatch==0.1.0'
      - run: 'sudo pip install mkdocs-bootstrap==0.1.1'
      - run: 'sudo pip install mkdocs==0.15.3'
      - run: 'sudo pip install mkdocs-material==0.2.4'
      - run: 'sudo pip install pymdown-extensions'
      - run: 'mkdocs build --clean'
      # Sync and delete any old files from the S3 bucket.
      - run: 'aws s3 sync site/ s3://$AWS_S3_BUCKET --acl public-read --cache-control "max-age=86400" --exclude "*.py*" --delete'
      # Allow `awscli` to make requests to CloudFront.
      - run: 'aws configure set preview.cloudfront true'
      # Invalidate every object.
      - run: 'aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
